---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Сайт должен иметь мобильную версию.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Кнопки В корзину лучше расположить в один ряд по 3 на странице.
  - Меню Категория не переведено на русский язык.
  - Лучше унифицировать фон на котором расположен товар. Сейчас это или черный, или белый, или цветной.
  - На основной странице не отображается размер скидки. Его не видно. Нужно, чтобы был виден.
  - Описание товара и Скидка (Off) не переводятся на русский язык при переключении на русскоязычную версию сайта.
  - На титульной странице не отображаются пробелы между ценой до скидки, ценой со скидкой, размером скидки.
