---
functional:
  - Пользователь должен иметь возможность искать товары по ключевому слову или категории.
  - Сайт должен иметь мобильную версию.
  - Пользователь должен иметь возможность фильтровать товары по цене, цвету, размеру и т.д.
  - Пользователь должен иметь возможность просматривать товары и просматривать подробную информацию о товаре.
  - Пользователь должен иметь возможность добавлять товары в корзину и просматривать содержимое корзины.
non-functional:
  - Сайт должен быть безопасным и защищать данные пользователя.
  - Веб-сайт должен быть разработан с учетом удобства использования и оптимизирован для скорости работы.
  - Сайт должен быть способен обрабатывать большое количество трафика.
  - Сайт должен быть протестирован на совместимость с последними версиями браузеров.
  - Сайт должен быть доступен на различных устройствах.
implicit:
  - Кнопки В корзину лучше расположить РОВНО по 3 кнопки в ряду.
  - Описание товаров не переводится на русский язык при переключении на русскоязычную версию сайта..
  - На титульной странице интернет магазина не отображается целиком размер скидки на товар. Его не видно, т.к. на него наползает кнопка "В корзину". Нужно, чтобы размер скидки был виден полностью.
  - На титульной странице не отображаются пробелы между ценой до скидки, ценой со скидкой, размером скидки.
